### ISSUE TITLE
Persistent models example?

### ISSUE THREAD

**Issue by bubenkoff** [bluele/factory-go#2]
Thanks for the great project!
How do i make a side effect for the model initialization (i need to store it in the database)?

**Comment by bluele** [comment]
@bubenkoff 
Thanks your comment. Here is an example for integration with [gorm](https://github.com/jinzhu/gorm).
https://gist.github.com/bluele/7babe26567785a198bb0bd813543ca86

**Comment by bubenkoff** [comment]
thank you!
so from that example, factories are not responsible for the persistence, still
and calling the persistence manually (like in the example) will mean that dependency graph has to be followed by the user himself

**Comment by bluele** [comment]
Yes. Currently this project has no support for directly integration with ORM like gorm, so users need to do manually.

**Comment by bubenkoff** [comment]
ok thanks
should i close this, or will you make a change to readme?

**Comment by bluele** [comment]
Thanks, I have added a description about this issue to README at de202b265ca70206ae8d654d139e1b39676815b0 .
I'll close this issue.
