### ISSUE TITLE
Allow options to be set for relations, not only for main object

### ISSUE THREAD

**Issue by bubenkoff** [bluele/factory-go#3]
as it is in in factorygirl, would be very useful if factory-fo support setting options for related objects (separated by dot):

```
user := factory.UserFactory.MustCreateWithOption(map[string]interface{}{"Role.RoleId": 2})
```

**Comment by bluele** [comment]
Thanks! I'll consider it.

**Comment by bluele** [comment]
#8 resolved this issue.

**Comment by bubenkoff** [comment]
@bluele thanks a lot!
